# Generated by Django 5.2 on 2025-04-09 04:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание (англ.)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание (кырг.)'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ky',
            field=models.TextField(blank=True, verbose_name='Краткое описание (кырг.)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (кырг.)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название категории (англ.)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название категории (кырг.)'),
        ),
    ]
