# Generated by Django 4.2.7 on 2025-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название корпуса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='buildings/', verbose_name='Изображение')),
                ('address', models.TextField(verbose_name='Адрес корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('mission', models.TextField(verbose_name='Миссия университета')),
                ('hymn', models.TextField(verbose_name='Гимн университета')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(upload_to='university/', verbose_name='Логотип')),
                ('banner', models.ImageField(upload_to='university/', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Информация об университете',
                'verbose_name_plural': 'Информация об университете',
            },
        ),
    ]
