# Generated by Django 4.2.7 on 2025-04-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('organizer', models.CharField(max_length=255, verbose_name='Организатор')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Срок регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('authors', models.TextField(verbose_name='Авторы')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('type', models.CharField(choices=[('article', 'Статья'), ('book', 'Книга'), ('conference', 'Конференция'), ('patent', 'Патент')], max_length=20, verbose_name='Тип')),
                ('journal', models.CharField(max_length=255, verbose_name='Журнал/Издательство')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Том')),
                ('issue', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страницы')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('abstract', models.TextField(verbose_name='Аннотация')),
                ('keywords', models.TextField(verbose_name='Ключевые слова')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Файл')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='research_areas/', verbose_name='Изображение')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Научное направление',
                'verbose_name_plural': 'Научные направления',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('leader', models.CharField(max_length=255, verbose_name='Руководитель')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='science.researcharea', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Научный проект',
                'verbose_name_plural': 'Научные проекты',
            },
        ),
    ]
